### ISSUE TITLE
all channels showing as offline

### ISSUE THREAD

**Issue by asolochek** [gordlea/home-assistant-addons#37]
I just set this up, and using the default mqtt setup I see my fireboard appear on my mqtt broker, and upon initial connection I get the current temperature of the probes as the "state", however I also get "offline" on the availability topic. I get no temperature updates beyond the initial value, and in the integration all channels simply show "offline."

The log (verbose, although that doesn't seem to make a difference) is:

10:27:26] INFO: Preparing to start...
[10:27:26] INFO: Verbose logging enabled.
[fireboard2mqtt:cli] starting fireboard2mqtt
[fireboard2mqtt:cli] initializing mqtt client...
[fireboard2mqtt:cli] mqtt client ready.
[fireboard2mqtt:mqttclient] connecting to mqtt
[fireboard2mqtt:mqttclient] connected to mqtt broker mqtt://core-mosquitto:1883
[fireboard2mqtt:controller] initializing fireboard device GM9GJR6G7
/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:216
        const speedPercentage = updateLog.speedPercentage;
                                          ^
TypeError: Cannot read properties of undefined (reading 'speedPercentage')
    at Fireboard.getDrivePayload (/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:216:43)
    at Fireboard.updateDrive (/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:153:31)
    at Fireboard.start (/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:182:14)
    at Controller.start (/opt/fireboard2mqtt/lib/Controller.js:38:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by mattdevo1** [comment]
I have the exact same issue. Running Home Assistant 2023.7 and the latest fireboard2mqtt version 2.0.1 from this repo. Any thoughts @gordlea?

[22:31:12] INFO: Preparing to start...
[fireboard2mqtt:cli] starting fireboard2mqtt
[fireboard2mqtt:cli] initializing mqtt client...
[fireboard2mqtt:cli] mqtt client ready.
[fireboard2mqtt:mqttclient] connecting to mqtt
[fireboard2mqtt:mqttclient] connected to mqtt broker mqtt://10.10.20.167:1883
[fireboard2mqtt:controller] initializing fireboard device GJKK6737J
/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:216
const speedPercentage = updateLog.speedPercentage;
^
TypeError: Cannot read properties of undefined (reading 'speedPercentage')
at Fireboard.getDrivePayload (/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:216:43)
at Fireboard.updateDrive (/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:153:31)
at Fireboard.start (/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:182:14)
at Controller.start (/opt/fireboard2mqtt/lib/Controller.js:38:23)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by gordlea** [comment]
https://github.com/gordlea/fireboard2mqtt/issues/8#issuecomment-1656749749

**Comment by gordlea** [comment]
This should be fixed with gordlea/fireboard2mqtt#40
