### ISSUE TITLE
mqtt doesn't connect when a custom broker is provided

### ISSUE THREAD

**Issue by asolochek** [gordlea/home-assistant-addons#38]
When I specify a mqtt broker to use, this addon does not connect. If I specify in the form X.X.X.X:1883 the log simply stops here:

[10:34:16] INFO: Preparing to start...
[10:34:16] INFO: Verbose logging enabled.
[fireboard2mqtt:cli] starting fireboard2mqtt
[fireboard2mqtt:cli] initializing mqtt client...
[fireboard2mqtt:cli] mqtt client ready.
[fireboard2mqtt:mqttclient] connecting to mqtt

If I just enter the IP address, the log looks like this:

[10:32:40] INFO: Preparing to start...
[fireboard2mqtt:cli] starting fireboard2mqtt
[fireboard2mqtt:cli] initializing mqtt client...
[fireboard2mqtt:cli] mqtt client ready.
[fireboard2mqtt:mqttclient] connecting to mqtt
/opt/fireboard2mqtt/.yarn/cache/mqtt-npm-4.3.7-42cab96512-8d4b655d61.zip/node_modules/mqtt/lib/connect/index.js:72
      throw new Error('Missing protocol')
            ^
Error: Missing protocol
    at Object.connect (/opt/fireboard2mqtt/.yarn/cache/mqtt-npm-4.3.7-42cab96512-8d4b655d61.zip/node_modules/mqtt/lib/connect/index.js:72:13)
    at MqttClient.connect (/opt/fireboard2mqtt/lib/MqttClient.js:13:28)
    at Controller.start (/opt/fireboard2mqtt/lib/Controller.js:16:25)
    at Object.<anonymous> (/opt/fireboard2mqtt/cli.js:23:12)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require$$0.Module._extensions..js (/opt/fireboard2mqtt/.pnp.cjs:14291:33)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.require$$0.Module._load (/opt/fireboard2mqtt/.pnp.cjs:14110:22)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)

**Comment by mattdevo1** [comment]
I have the exact same issue. Running Home Assistant 2023.7 and the latest fireboard2mqtt version 2.0.1 from this repo.

[22:31:12] INFO: Preparing to start...
[fireboard2mqtt:cli] starting fireboard2mqtt
[fireboard2mqtt:cli] initializing mqtt client...
[fireboard2mqtt:cli] mqtt client ready.
[fireboard2mqtt:mqttclient] connecting to mqtt
[fireboard2mqtt:mqttclient] connected to mqtt broker mqtt://10.10.20.167:1883
[fireboard2mqtt:controller] initializing fireboard device GJKK6737J
/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:216
        const speedPercentage = updateLog.speedPercentage;
                                          ^
TypeError: Cannot read properties of undefined (reading 'speedPercentage')
    at Fireboard.getDrivePayload (/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:216:43)
    at Fireboard.updateDrive (/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:153:31)
    at Fireboard.start (/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:182:14)
    at Controller.start (/opt/fireboard2mqtt/lib/Controller.js:38:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by gordlea** [comment]
https://github.com/gordlea/fireboard2mqtt/issues/8#issuecomment-1656749749

**Comment by gordlea** [comment]
I've reproduced this, working on it now: https://github.com/gordlea/fireboard2mqtt/issues/16

**Comment by gordlea** [comment]
Fixed with #54
