### ISSUE TITLE
Speed percentage issue 

### ISSUE THREAD

**Issue by alexownsall** [gordlea/home-assistant-addons#39]
I don't have a drive but it's coming up with this error when I try to run now. 

/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:216
        const speedPercentage = updateLog.speedPercentage;
                                          ^
TypeError: Cannot read properties of undefined (reading 'speedPercentage')
    at Fireboard.getDrivePayload (/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:216:43)
    at Fireboard.updateDrive (/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:153:31)
    at Fireboard.start (/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:182:14)
    at Controller.start (/opt/fireboard2mqtt/lib/Controller.js:38:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by alexownsall** [comment]
It sends the mqtt messages and creates the device and all, but the plug in crashes

**Comment by gordlea** [comment]
https://github.com/gordlea/fireboard2mqtt/issues/8#issuecomment-1656749749

**Comment by fdelacou** [comment]
I have exactly the same issue except that I have a Spark so there is no speed percentage. And also same in the sense that this is crashing the add-on.

[fireboard2mqtt:controller] initializing fireboard device G8KGMD3GJ
[fireboard2mqtt:fireboard:G8KGMD3GJ] begin pinging fireboard internalIP (192.168.0.113) every 10000ms
[fireboard2mqtt:controller] initializing fireboard device GFDK7D9R2
/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:216
        const speedPercentage = updateLog.speedPercentage;
                                          ^

TypeError: Cannot read properties of undefined (reading 'speedPercentage')
    at Fireboard.getDrivePayload (/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:216:43)
    at Fireboard.updateDrive (/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:153:31)
    at Fireboard.start (/opt/fireboard2mqtt/lib/fireboard/Fireboard.js:182:14)
    at Controller.start (/opt/fireboard2mqtt/lib/Controller.js:38:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by gordlea** [comment]
This should be fixed with gordlea/fireboard2mqtt#40
